#!/usr/bin/env bash
getbookmarks() {
    sqlite3 -column -separator $'\t' ~/.local/share/buku/bookmarks.db \
    "select id || ' ' || trim(tags, ',') || ' ' || URL || ' ' || metadata from bookmarks order by tags"
}

menu=$(getbookmarks | dmenu -l 10 -i -p '>')
id="${menu%% *}"

buku -o "${id}"
