#!/usr/bin/perl

# gimap.pl by gxmsgx
# description: get the count of unread messages on gmail imap

use strict;
use Mail::IMAPClient;
use IO::Socket::SSL;

#my $username = 'example.username'; # example.username@gmail.com
#my $password = 'password123';

my $username = $ENV{'GMAIL_USERNAME'} or die "GMAIL_USERNAME not set";
my $password = $ENV{'GMAIL_PASSWORD'} or die "GMAIL_PASSWORD not set";

my $socket = IO::Socket::SSL->new(
   PeerAddr => 'imap.gmail.com',
   PeerPort => 993,
  )
  or die "socket(): $@";

my $client = Mail::IMAPClient->new(
   Socket   => $socket,
   User     => $username,
   Password => $password,
  )
  or die "new(): $@";

if ($client->IsAuthenticated()) {
    my $msgct;

    $client->select("INBOX");
    $msgct = $client->unseen_count||'0';
    print "$msgct\n";
}

$client->logout();
