#!/usr/bin/env python
from mpd import MPDClient
import csv
import os,sys


def mainLoop(mpdClient,logfile):
    print("# Entering main loop...")
    previousFile = None

    while True:
        mpdClient.idle("player")
        if mpdClient.status()["state"] != "play":
            continue
        song = mpdClient.currentsong()
        if song["file"] == previousFile:
            continue
        previousFile = song["file"]
        scrobbled_parts = [song["artist"], song["title"]]
        print("# PLAYING:")
        print(previousFile)
        with open(logfile,'a') as csvfile:
            logwriter = csv.writer(csvfile)
            logwriter.writerow([previousFile])

def main():
    client = MPDClient()
    client.connect("localhost", 6600)
    logfile=os.environ['HOME']+"/.local/share/linn/mpdlog.csv"
    mainLoop(client,logfile)

if __name__ == "__main__":
    main()
