#!/usr/bin/env bash

xdg-mime default nsxiv.desktop image/png
xdg-mime default nsxiv.desktop image/jpeg
xdg-mime default nsxiv.desktop image/jpg
xdg-mime default nsxiv.desktop image/gif
xdg-mime default nsxiv.desktop image/webp
xdg-mime default nsxiv.desktop image/bmp
xdg-mime default nsxiv.desktop image/tiff

xdg-mime default org.gnome.Evince.desktop application/pdf
